name: GroupProject
version: ${project.version}
main: com.port.groupproject.GroupProject
authors: [ Jasper ]
commands:
  hammer:
    description: Gives player a hammer.
    usage: /<command>
    aliases: [ gphammer ]
  felling:
    description: Gives player a felling axe.
    usage: /<command>
    aliases: [ gpfelling ]
  veinminer:
    description: Gives player a vein mining pickaxe.
    usage: /<command>
    aliases: [ gpveinminer, vminer ]